#!/usr/bin/env bash
#Script to configure Nginx server with a custom header
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i 's/http {/&\n\tadd_header X-Served-By $hostname;/' /etc/nginx/nginx.conf
service nginx restart

