#!/usr/bin/env bash
#Bash script that displays a message when it is terminated
_term()
{
   echo 'I am invisible!!!'
}
trap_term SIGTERM
while "true"
do
   echo 'To infinity and beyond'
   sleep 2
done
